
package chat_apps;
//import static chats.chat_client.dout;
import java.awt.event.KeyEvent;
import java.awt.*;
import javax.swing.*;
import java.net.*;
import java.io.*;
import java.util.StringTokenizer;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 *
 * @author Belayneh
 */
public class Chatter_server extends JFrame {

    static ServerSocket ss;
    static Socket s;
    static DataInput din;
    static DataOutput dout;
    public static String username=null;
    public static int count=0,stop=0,text_field=0;
    JFrame frame;
    
    public Chatter_server() {
        //Chatters cht=new Chatters();
        initComponents();
        
    }
    public Chatter_server(String usernme) {
        
        username=usernme;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        msg_send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contacts = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quit = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        file_choose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        belayneh = new javax.swing.JLabel();
        selamu = new javax.swing.JLabel();
        yohannes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        group_ComboBox = new javax.swing.JComboBox();
        user1 = new javax.swing.JLabel();
        connect = new javax.swing.JButton();
        get_helps = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat App");
        setBackground(new java.awt.Color(51, 255, 255));
        setLocation(new java.awt.Point(140, 60));
        setResizable(false);

        msg_area.setBackground(new java.awt.Color(153, 255, 255));
        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        msg_text.setToolTipText("chat with your friend");
        msg_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msg_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                msg_textFocusLost(evt);
            }
        });
        msg_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_textActionPerformed(evt);
            }
        });
        msg_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_textKeyPressed(evt);
            }
        });

        msg_send.setText("send");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });

        jLabel1.setText("you are chatting with your friend.");

        contacts.setForeground(new java.awt.Color(0, 0, 255));
        contacts.setText("Contacts:");
        contacts.setToolTipText("click to see lists");
        contacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Group:");

        quit.setForeground(new java.awt.Color(255, 0, 102));
        quit.setText("Close");
        quit.setToolTipText("Stop Your Conversetion");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Engineer 2\\4th year\\Projects\\Datacom\\Java Project\\Project\\chat photos\\1\\use this or\\photo profile_good2.PNG")); // NOI18N
        jLabel4.setToolTipText("Your  Friend");
        jLabel4.setMaximumSize(new java.awt.Dimension(80, 60));
        jLabel4.setMinimumSize(new java.awt.Dimension(60, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 20));

        user.setForeground(new java.awt.Color(0, 153, 255));

        file_choose.setForeground(new java.awt.Color(0, 153, 255));
        file_choose.setText("File Chooser");
        file_choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_chooseActionPerformed(evt);
            }
        });

        jLabel6.setText("share file");

        belayneh.setText("Belayneh");
        belayneh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                belaynehMouseClicked(evt);
            }
        });

        selamu.setText("Selamu");
        selamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selamuMouseClicked(evt);
            }
        });

        yohannes.setText("Yohannes");
        yohannes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yohannesMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel7.setText("please select the group !");

        group_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chat Groups", "Belayneh", "Selamu", "Yohannes", "" }));
        group_ComboBox.setToolTipText("Select chat Group !");
        group_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group_ComboBoxActionPerformed(evt);
            }
        });

        user1.setText("User");

        connect.setForeground(new java.awt.Color(0, 51, 255));
        connect.setText("Create Connection");
        connect.setToolTipText("please click here!");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        get_helps.setForeground(new java.awt.Color(0, 153, 255));
        get_helps.setText("help");
        get_helps.setToolTipText("Click here");
        get_helps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                get_helpsMouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 102, 204));
        jLabel5.setText("?");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connect)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(get_helps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(msg_text, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(msg_send, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(quit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(file_choose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contacts)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selamu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yohannes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(belayneh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(group_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(get_helps)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user1))
                        .addGap(12, 12, 12)
                        .addComponent(user))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(contacts))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(group_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(belayneh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selamu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yohannes)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(connect)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(file_choose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(msg_text)
                            .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        // TODO add your handling code here:
        try{
          String msgout;
          msgout=msg_text.getText().trim();
          if(!msgout.equals("enter chat message!")||text_field==0){
           dout.writeUTF(msgout);
             
           }
          
        }
        catch(Exception e){
          //e.printStackTrace();
        }
    }//GEN-LAST:event_msg_sendActionPerformed

    private void msg_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_textActionPerformed
        // TODO add your handling code here:
        text_field=0;
    }//GEN-LAST:event_msg_textActionPerformed

    private void msg_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_textKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
         try{
          String msgout;
          msgout=msg_text.getText().trim();
            dout.writeUTF(msgout);
              text_field=10;
              text_field=0;
        }
        catch(Exception e){
           //e.printStackTrace();
        }  
       }
    }//GEN-LAST:event_msg_textKeyPressed

    private void msg_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msg_textFocusGained
        // TODO add your handling code here:
        try{
          //String msgout="";
          msg_text.setText("");
          msg_text.setForeground(Color.BLACK);
            text_field=0;
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_msg_textFocusGained

    private void msg_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msg_textFocusLost
        // TODO add your handling code here:
        try{
           //String msgout="";
           if(msg_text.getText().isEmpty()){ 
             msg_text.setText("enter chat message!");
               msg_text.setForeground(Color.darkGray);
                text_field++;
            }
           
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_msg_textFocusLost

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(-1);
    }//GEN-LAST:event_quitActionPerformed

    private void file_chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_chooseActionPerformed
        // TODO add your handling code here:
        try{
          String msgout;
           String msgout2;
             //String []msgout3;
          JFileChooser chooser=new JFileChooser();
           chooser.showOpenDialog(null);
           File f=chooser.getSelectedFile();
           //msgout=f.getAbsolutePath();
           msgout=f.getAbsoluteFile().getName();
                //String []msgout3=new String[msgout.length()];
                 StringTokenizer st = new StringTokenizer(msgout);       
                          msgout2=st.nextToken("\\");
          //msgout=msg_text.getText().trim();
                /*while(st.hasMoreTokens()){             
                       msgout2=st.nextToken("\\.");
                        if(!st.hasMoreTokens()){
                            dout.writeUTF(msgout2);
                            //dout.writeUTF(msgout2+"\n");
                          }  
                 }*/
           dout.writeUTF(msgout);
        }
        catch(Exception e){
              //e.printStackTrace();
        }
    }//GEN-LAST:event_file_chooseActionPerformed

    private void belaynehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_belaynehMouseClicked
        // TODO add your handling code here:
        try{
             String name="";
             name=belayneh.getText();
             if(user1.getText().isEmpty()){
               user1.setText(name);
             }
             else{
                 user1.setText("");
                user1.setText(name);
              }
                 
                   isempty(name);
            
         }
        catch(Exception e){
        
         }
    }//GEN-LAST:event_belaynehMouseClicked

    private void group_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_ComboBoxActionPerformed
        // TODO add your handling code here:
        try{
             String name="";
                  String selected;
                  selected=(String)group_ComboBox.getSelectedItem();
                if(selected.equals("Belayneh")){
                    //frame=new JFrame("");
                    user1.setText("Belayneh");   
                    //frame=new JFrame("Belayneh");
                    this.username="Belayneh";
                    //username=
                    
                }  
                else if(selected.equals("Selamu")){
                    user1.setText("Selamu");
                        this.username="Selamu";
                    } 
                else if(selected.equals("Yohannes")){
                    user1.setText("Yohannes");
                       username="Yohannes";
                 }
            
         }
        catch(Exception e){
        
         }
    }//GEN-LAST:event_group_ComboBoxActionPerformed

    private void selamuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selamuMouseClicked
        // TODO add your handling code here:
        try{
             String name="";
             name=selamu.getText();
             if(user1.getText().isEmpty()){
               user1.setText(name);
             }
             else{
                 user1.setText("");
                user1.setText(name);
              }
              isempty(name);
           
         }
        catch(Exception e){
        
         }
    }//GEN-LAST:event_selamuMouseClicked

    private void yohannesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yohannesMouseClicked
        // TODO add your handling code here:
        try{
             String name="";
             name=yohannes.getText();
             if(user1.getText().isEmpty()){
               user1.setText(name);
             }
             else{
                 user1.setText("");
                user1.setText(name);
              }
              isempty(name);
            
         }
        catch(Exception e){
        
         }
    }//GEN-LAST:event_yohannesMouseClicked

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        // TODO add your handling code here:
        Thread t = new Thread() {
           @Override
               public void run() {  // override the run() for the running behaviors      
           
            try{
                //connect.setVisible(false);
             Chatter_client cht_cl=new Chatter_client("user");
             cht_cl.setVisible(true);
                        try {
                        sleep(10);  // milliseconds
                     } 
                     catch (InterruptedException ex) {}
             
              }
            catch(Exception ex){
                //System.out.println("error in input!");
            }
         }
        }; 
        t.start();  // call back run() 
      
    }//GEN-LAST:event_connectActionPerformed

    private void get_helpsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_get_helpsMouseClicked
        // TODO add your handling code here:
        try{
           
            EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                display();    //displays help for the user
            }
        });
            
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_get_helpsMouseClicked

    private void contactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsMouseClicked
        // TODO add your handling code here:
     try{
       if(!belayneh.isShowing()){
        belayneh.setVisible(true);
         }
       else{
           belayneh.setVisible(false);
       }
       if(!selamu.isShowing()){
        selamu.setVisible(true);
        }
       else{
          selamu.setVisible(false);
       }
       if(!yohannes.isShowing()){
        yohannes.setVisible(true);
       }
       else{
          yohannes.setVisible(false);
       }
      }
     catch(Exception ex){
     
      }
  
    }//GEN-LAST:event_contactsMouseClicked

    /**
     * @param args the command line arguments
     */
    //public static void main_do(){
    public static void main(String args[]) {
     if(stop==0){
          splash spl=new splash();
          spl.setVisible(true);
        try{
            for(int i=0;i<=50;i++){
             Thread.sleep(80);
             spl.loading_num.setText(Integer.toString(2*i)+"%");
             spl.loading_Bar.setValue(2*i);
                 spl.dot1.setText(".");
                 spl.dot2.setText(".");
                 spl.dot3.setText(".");
                    Thread.sleep(80);
                 spl.dot1.setText("");
                 spl.dot2.setText("");
                 spl.dot3.setText("");
               if(i==50){   
                    spl.setVisible(false);
                    //log.setVisible(true);
                    
                }
            }
          }
         catch(Exception e){
          
          }      
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chatter_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chatter_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chatter_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chatter_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chatter_server().setVisible(true);
                    belayneh.setVisible(false);
                    selamu.setVisible(false);
                    yohannes.setVisible(false);
                stop=10;
            }
        });
            
        String msgin="";
        try{
            
           ss=new ServerSocket(1201);
           s=ss.accept();              //server accepts the client's request and the connection setup at port 1201
             int checknew=0;
             String firstuser=null,mdate=null,mtime=null;
             firstuser=username;
           din=new DataInputStream(s.getInputStream());
           dout=new DataOutputStream(s.getOutputStream());
           
           while(true){
             try{  
               msgin=din.readUTF();
                         int hr = LocalTime.now().getHour();
                     mtime=(hr == 0 || hr == 12 ? 12 : hr % 12) + ":" + LocalTime.now().getMinute()+":"+LocalTime.now().getSecond() + (hr >= 12 ? " PM" : " AM");
                     mdate=LocalDate.now().toString();
              if(username!=null){          
               if(!username.equals(firstuser)){
                 msg_area.setText(msg_area.getText().trim()+"\n "+username+":\t "+msgin+"\t"+mdate+"\t"+mtime);
                 firstuser=username;
               }
               else if(username.equals(firstuser)){
                 msg_area.setText(msg_area.getText().trim()+"\n \t "+msgin+"\t"+mdate+"\t"+mtime);       
               }
              }
               else {
                  if(checknew==0){
                  msg_area.setText(msg_area.getText().trim()+"\n Belayneh:\t "+msgin+"\t"+mdate+"\t"+mtime);
                   checknew++;
                  }
                  else
                      msg_area.setText(msg_area.getText().trim()+"\n \t "+msgin+"\t"+mdate+"\t"+mtime);
                }
              }
            catch(Exception ex){
                //ex.printStackTrace();
             }
            } 
         }
        catch(Exception e){
          e.printStackTrace();
        }
    }
    public static String isempty(String usern){
        username=usern;
        return usern;
    }
    public static String isempty(){
        return null;
    }
    private static void display() {
         JTextArea field1 = new JTextArea();
          JPanel panel = new JPanel(new FlowLayout());//0,1 
      panel.add(new JLabel("Read !"));
        panel.add(field1);
         panel.setBackground(Color.blue);
      
            field1.setText("Procedures to use:\n\n  First you have to create a connection to start.\n  Hence,\n  1. Press <Create Connection> button."
                    + "\n  Have you seen a new form?\n  If so,\n   Do conversetion.\n\nDevelopers:\n\tBelayneh,\n\tSelamu,\n\tYohannes"
                    + "\n\n\tAt AAIT Ethiopia.\n\nProduct: \n\tversion 1:  0.0.0");
     
            int result = JOptionPane.showConfirmDialog(null, panel, "help",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println("Good BYE!!");
        } else {
            System.out.println("Cancelled");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel belayneh;
    public static javax.swing.JButton connect;
    public static javax.swing.JLabel contacts;
    private javax.swing.JButton file_choose;
    public static javax.swing.JLabel get_helps;
    public javax.swing.JComboBox group_ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public static final javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_send;
    private javax.swing.JTextField msg_text;
    private javax.swing.JButton quit;
    public static javax.swing.JLabel selamu;
    public javax.swing.JLabel user;
    public static javax.swing.JLabel user1;
    public static javax.swing.JLabel yohannes;
    // End of variables declaration//GEN-END:variables
}
