
package chat_apps;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.*;
import java.net.*;
import java.io.*;
import java.util.StringTokenizer;
import javax.swing.*;
import java.time.LocalDate;
import java.time.LocalTime;

//import java.io
/**
 *
 * @author Belayneh
 */
public class Chatter_client extends javax.swing.JFrame {

    static Socket s;
    static DataInput din;
    static DataOutput dout;
    
    JFrame frame;
    public static String username=null,msgin;
    public static int count=0,stop=0,text_field=0;
    
    public Chatter_client() {
        initComponents();
    }
    public Chatter_client(String usernme) {
        main_do();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        msg_send = new javax.swing.JButton();
        contacts = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quit = new javax.swing.JButton();
        user2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        file_choose = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        group_ComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        belayneh = new javax.swing.JLabel();
        selamu = new javax.swing.JLabel();
        yohannes = new javax.swing.JLabel();
        get_help = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat App");
        setLocation(new java.awt.Point(680, 60));
        setResizable(false);

        msg_area.setBackground(new java.awt.Color(153, 255, 255));
        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        msg_text.setToolTipText("chat with your friend");
        msg_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msg_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                msg_textFocusLost(evt);
            }
        });
        msg_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_textActionPerformed(evt);
            }
        });
        msg_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_textKeyPressed(evt);
            }
        });

        msg_send.setText("send");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });

        contacts.setForeground(new java.awt.Color(0, 51, 255));
        contacts.setText("Contacts:");
        contacts.setToolTipText("click to see lists");
        contacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Group:");

        jLabel3.setText("you are chatting with your friend.");

        quit.setForeground(new java.awt.Color(255, 0, 51));
        quit.setText("Close");
        quit.setToolTipText("Stop Your Conversetion");
        quit.setActionCommand("Close");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        user2.setForeground(new java.awt.Color(0, 204, 255));

        jLabel5.setBackground(new java.awt.Color(204, 255, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Engineer 2\\4th year\\Projects\\Datacom\\Java Project\\Project\\chat photos\\1\\use this or\\photo profile_good2.PNG")); // NOI18N
        jLabel5.setToolTipText("Your  Friend ");

        file_choose.setForeground(new java.awt.Color(0, 153, 255));
        file_choose.setText("File Chooser");
        file_choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_chooseActionPerformed(evt);
            }
        });

        jLabel4.setText("share file");

        group_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chat Groups", "Belayneh", "Selamu", "Yohannes" }));
        group_ComboBox.setToolTipText("Select Chat Group !");
        group_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group_ComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel6.setText("please select the group !");

        user.setText("User");

        belayneh.setText("Belayneh");
        belayneh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                belaynehMouseClicked(evt);
            }
        });

        selamu.setText("Selamu");
        selamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selamuMouseClicked(evt);
            }
        });

        yohannes.setText("Yohannes");
        yohannes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yohannesMouseClicked(evt);
            }
        });

        get_help.setForeground(new java.awt.Color(0, 153, 153));
        get_help.setText("help ");
        get_help.setToolTipText("Click here");
        get_help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                get_helpMouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("?");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(get_help)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contacts)
                            .addComponent(selamu)
                            .addComponent(belayneh)
                            .addComponent(yohannes))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(group_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(msg_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(msg_send, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(file_choose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(get_help)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(contacts))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(group_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(belayneh)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selamu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yohannes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(file_choose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(msg_text)
                    .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        // TODO add your handling code here:
        try{
          String msgout="";
          msgout=msg_text.getText().trim();
          if(!msgout.equals("enter chat message!")||text_field==0){
            dout.writeUTF(msgout);
          }
          
        }
        catch(Exception e){
         e.printStackTrace();
        }
    }//GEN-LAST:event_msg_sendActionPerformed

    private void msg_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msg_textActionPerformed

    private void msg_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_textKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
         try{
          String msgout="";
          msgout=msg_text.getText().trim();
          dout.writeUTF(msgout);
          
        }
        catch(Exception e){
          e.printStackTrace();
        }  
       }     
            
    }//GEN-LAST:event_msg_textKeyPressed

    private void msg_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msg_textFocusGained
        // TODO add your handling code here:
        try{
          //String msgout="";
          msg_text.setText("");
          msg_text.setForeground(Color.BLACK);
           text_field=0;
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_msg_textFocusGained

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(-1);
    }//GEN-LAST:event_quitActionPerformed

    private void msg_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msg_textFocusLost
        // TODO add your handling code here:
        try{
           //String msgout="";
           if(msg_text.getText().isEmpty()){ 
             msg_text.setText("enter chat message!");
               msg_text.setForeground(Color.darkGray);
                text_field++;
            }
          //else
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_msg_textFocusLost

    private void file_chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_chooseActionPerformed
        // TODO add your handling code here:
        try{
          String msgout;
           String msgout2;
             //String []msgout3;
          JFileChooser chooser=new JFileChooser();
           chooser.showOpenDialog(null);
           File f=chooser.getSelectedFile();
           //msgout=f.getAbsolutePath();
                msgout=f.getAbsoluteFile().getName();
                //String []msgout3=new String[msgout.length()];
                 //StringTokenizer st = new StringTokenizer(msgout);       
                          //msgout2=st.nextToken("\\.");
                /*while(st.hasMoreTokens()){             
                       msgout2=st.nextToken("\\");
                        if(!st.hasMoreTokens()){
                            dout.writeUTF(msgout2);
                            //dout.writeUTF(msgout2+"\n");
                          }  
                 }*/
           dout.writeUTF(msgout);
        }
        catch(Exception e){
              //e.printStackTrace();
        }
    }//GEN-LAST:event_file_chooseActionPerformed

    private void group_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_ComboBoxActionPerformed
        // TODO add your handling code here:
        try{
             String name="";
                  String selected;
                  selected=(String)group_ComboBox.getSelectedItem();
                if(selected.equals("Belayneh")){
                    //frame=new JFrame("");
                    user.setText("Belayneh");   
                    //frame=new JFrame("Belayneh");
                    this.username="Belayneh";
                }  
                else if(selected.equals("Selamu")){
                    user.setText("Selamu");
                        this.username="Selamu";
                    } 
                else if(selected.equals("Yohannes")){
                    user.setText("Yohannes");
                       username="Yohannes";
                 }
            
         }
        catch(Exception e){
        
         }
    }//GEN-LAST:event_group_ComboBoxActionPerformed

    private void belaynehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_belaynehMouseClicked
        // TODO add your handling code here:
        try{
             String name="";
             name=belayneh.getText();
             if(user.getText().isEmpty()){
               user.setText(name);
             }
             else{
                 user.setText("");
                user.setText(name);
              }
              isempty(name);
         }
        catch(Exception e){
        
         }
    }//GEN-LAST:event_belaynehMouseClicked

    private void selamuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selamuMouseClicked
        // TODO add your handling code here:
        try{
             String name="";
             name=selamu.getText();
             if(user.getText().isEmpty()){
               user.setText(name);
             }
             else{
                 user.setText("");
                user.setText(name);
              }
                 
              isempty(name);
            
         }
        catch(Exception e){
        
         }
    }//GEN-LAST:event_selamuMouseClicked

    private void yohannesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yohannesMouseClicked
        // TODO add your handling code here:
        try{
             String name="";
             name=yohannes.getText();
             if(user.getText().isEmpty()){
               user.setText(name);
             }
             else{
                 user.setText("");
                user.setText(name);
              }
                 
              isempty(name);
         }
        catch(Exception e){
        
         }
    }//GEN-LAST:event_yohannesMouseClicked

    private void get_helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_get_helpMouseClicked
        // TODO add your handling code here:
        try{
           
            EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                display();
            }
        });
            
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_get_helpMouseClicked

    private void contactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsMouseClicked
        try{
       if(!belayneh.isShowing()){
        belayneh.setVisible(true);
         }
       else{
           belayneh.setVisible(false);
       }
       if(!selamu.isShowing()){
        selamu.setVisible(true);
        }
       else{
          selamu.setVisible(false);
       }
       if(!yohannes.isShowing()){
        yohannes.setVisible(true);
       }
       else{
          yohannes.setVisible(false);
       }
      }
     catch(Exception ex){
     
      }
    }//GEN-LAST:event_contactsMouseClicked
     
    
    /**
     * @param args the command line arguments
     */
    public static void main_do(){
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chatter_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chatter_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chatter_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chatter_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     //Thread t = new Thread(); //{   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chatter_client().setVisible(true);
                    belayneh.setVisible(false);
                    selamu.setVisible(false);
                    yohannes.setVisible(false);
            }
        });
        try{
             int checknew=0;
             String firstuser=null,mdate=null,mtime=null;
             firstuser=username;
           s=new Socket("127.0.01",1201);//client
                 Chatter_server.connect.setVisible(false);//after connection setup it will disappear
           din=new DataInputStream(s.getInputStream());
           dout=new DataOutputStream(s.getOutputStream());
        
           while(true){
            try{
               msgin=din.readUTF();
                        int hr = LocalTime.now().getHour();
                     mtime=(hr == 0 || hr == 12 ? 12 : hr % 12) + ":" + LocalTime.now().getMinute()+":"+LocalTime.now().getSecond() + (hr >= 12 ? " PM" : " AM");
                     mdate=LocalDate.now().toString();
              if(username!=null){       
               if(!username.equals(firstuser)){
                 msg_area.setText(msg_area.getText().trim()+"\n "+username+":\t "+msgin+"\t"+mdate+"\t"+mtime);
                 firstuser=username;
               }
               else if(username.equals(firstuser)){
                 msg_area.setText(msg_area.getText().trim()+"\n \t "+msgin+"\t"+mdate+"\t"+mtime);  
               }
              }
              else{
               if(checknew==0){
                  msg_area.setText(msg_area.getText().trim()+"\n Selamu:\t "+msgin+"\t"+mdate+"\t"+mtime);
                   checknew++;
                  }
                  else
                      msg_area.setText(msg_area.getText().trim()+"\n \t "+msgin+"\t"+mdate+"\t"+mtime);  
                }
              }
            catch(Exception ex){
                //ex.printStackTrace();
             }
             
           }  
            
         }
        catch(Exception e){
          e.printStackTrace();
        }
    }
    
    public static void isempty(String usern){
        username=usern;
        isempty();
     }
    public static String isempty(){
        //username=usern;
        return username;
    }
    private static void display() {
        JTextArea field1 = new JTextArea();
          JPanel panel = new JPanel(new FlowLayout());//0,1 
//      panel.add(new JLabel("Read !"));
        panel.add(field1);
         panel.setBackground(Color.blue);
        String selected;
            field1.setText("Procedures to use:\n\n  First you have to create a connection to start.\n  Hence,\n  1. Press <Create Connection> button."
                    + "\n  Have you seen a new form?\n  If so,\n   Do conversetion.\n\nDevelopers:\n\tBelayneh,\n\tSelamu,\n\tYohannes"
                    + "\n\n\tAt AAIT Ethiopia.\n\nProduct: \n\tversion 1:  0.0.0");
        
        int result = JOptionPane.showConfirmDialog(null, panel, "help",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println("Good BYE!!");
        } else {
            System.out.println("Cancelled");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel belayneh;
    public static javax.swing.JLabel contacts;
    private javax.swing.JButton file_choose;
    private javax.swing.JLabel get_help;
    public javax.swing.JComboBox group_ComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_send;
    private javax.swing.JTextField msg_text;
    private javax.swing.JButton quit;
    public static javax.swing.JLabel selamu;
    public static javax.swing.JLabel user;
    public javax.swing.JLabel user2;
    public static javax.swing.JLabel yohannes;
    // End of variables declaration//GEN-END:variables
}
